### PR TITLE
I added every script for task-3.

### PR DESCRIPTION
**Pull request by DenisBukva**
They are in the dir week-3 and in dir chapter 13, 14, 15 or 16.
Pictures of completed scripts:
**Chapter13:**
test-1
test-1

badtest-1
badtest-1

test-2
test-2

badtest-2
badtest-2

test-3
test-3

test-4
test-4

test-5
test-5

test-5b
test-5b

test-6
test-6

test-7
test-7

test-8
test-8

test-9
test-9

test-10
test-10

test-11
test-11

test-12
test-12

test-13
test-13

test-14
test-14

test-15
test-15

test-16
test-16

test-17
test-17

test-18
test-18

test-19
test-19

test-20
test-20

test-21
test-21

test-22
test-22

test-23
test-23

test-24
test-24

test-25
test-25

test-26
test-26

**Chapter-14**:
test-1
test-1

badtest1
badtest1

test-2
test-2

test-3
test-3

test-4
test-4

test-5
test-5

test-5b
test-5b

test-6
test-6

test-7
test-7

test-8
test-8

test-9
test-9

test-10
test-10

test-11
test-11

test-12
test-12

test-13
test-13

test-14
test-14

test-15
test-15

test-16
test-16

test-17
test-17

test-18
test-18

test-19
test-19

test-20
test-20

test-21
test-21

test-22
test-22

test-23
test-23

test-24
test-24

test-25
test-25

test-26
test-26

test-27
test-27

test-28
test-28

**Chapter-15**

badtest
badtest

test-3
test-3

test-4
test-4

test-5
test-5

test-6-7
test-6 and test-7

test-7
test-7

test-8-9
test-8 and test-9

test-10
test-10

test-11
test-11

test-12
test-12

test-13
test-13

test-14
test-14 sh

test-15
test-15

test-16
test-16

test-17
test-17

test-18
test-18

test-19
test-19

test-20
test-20

test-21
test-21

test-22
test-22

test-23
test-23

**Chapter-16**

test-1
test-1

test-2
test-2

test-3
test-3

test-3b
test-3b

test-4
test-4

test-5
test-5

test-6-7-8-9
test-6-7-8-9

test-10
test-10

test-11
test-11

test-11-12
test-11-12

test-12
test-12

test-13
test-13

test-13b
test13b

nohup command
nohup command

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please check the files which we don't need, like output files, temp files, etc.. you can leave .sql and .csv files as they are part from scripts.

**Comment by DenisBukva** [comment]
Boris, I removed all the files wich I don't need, let me know if I need to change anything else.

**Review by borisbradic — CHANGES_REQUESTED** [review]
You still have some output files in chapter14 and chapter15 directories.

**Comment by DenisBukva** [comment]
Boris, Now, I believe everything is okay, let me know if I need to change anything else.

**Review by borisbradic — CHANGES_REQUESTED** [review]
Check again chapter 15, are these output files? 

Screenshot from 2023-03-14 12-05-43

**Comment by DenisBukva** [comment]
This is the out files. I removed them.

**Review by borisbradic — APPROVED** [review]
Seems much better now.

**Pull request merged**
